### PR TITLE
Remove the workaround again.

### PR DESCRIPTION
**Pull request by haraldh**
You are right, that my patch did not work, if you replay the blockchain.
... But... your new version does not work for me, too.

So, here is an approach, which works for me.
I can copy wallets via NFC and the resync shows all transactions.

Thanks! :-)

### CODE REVIEW

**Comment by ksedgwic** [comment]
Cool, I'll take a look ASAP!

Here are the three cases I'm checking
1) new wallets should be fast
2) pairing (restore should be equiv) works
3) rescan works

Thanks again!

Ken

On Fri, Aug 1, 2014 at 9:52 AM, Harald Hoyer notifications@github.com
wrote:

> You are right, that my patch did not work, if you replay the blockchain.
> ... But... your new version does not work for me, too.
> 
> So, here is an approach, which works for me.
> I can copy wallets via NFC and the resync shows all transactions.
> 
> ## Thanks! :-)
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/haraldh/Wallet32 noworkaround
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/ksedgwic/Wallet32/pull/26
> Commit Summary
> - Revert "Restricted the workaround key to only cases where we aren't
>   creating a"
> - Revert "Revert "Remove workaround for fast catchup""
> - Use HDAddress.EPOCH every time for the keys
> - Set the PeerGroup to scan only from scanTime on
> 
> File Changes
> - _M_ src/com/bonsai/wallet32/HDWallet.java
>   https://github.com/ksedgwic/Wallet32/pull/26/files#diff-0 (32)
> - _M_ src/com/bonsai/wallet32/RestoreWalletActivity.java
>   https://github.com/ksedgwic/Wallet32/pull/26/files#diff-1 (4)
> - _M_ src/com/bonsai/wallet32/WalletService.java
>   https://github.com/ksedgwic/Wallet32/pull/26/files#diff-2 (8)
> - _M_ src/com/bonsai/wallet32/WalletUtil.java
>   https://github.com/ksedgwic/Wallet32/pull/26/files#diff-3 (4)
> 
> Patch Links:
> - https://github.com/ksedgwic/Wallet32/pull/26.patch
> - https://github.com/ksedgwic/Wallet32/pull/26.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ksedgwic/Wallet32/pull/26.

## 

Ken Sedgwick
Bonsai Software, Inc.
http://www.bonsai.com/ken/
(510) 269-7334
ken@bonsai.com
Public Key: http://www.bonsai.com/ken/ken.asc
GPG Fingerprint: 851E 3B07 E586 0843 9434  5CC7 4033 3B9B 3F3F 9640

**Comment by ksedgwic** [comment]
Harald,

This pull request works for me, so I merged it.

I did comment out altering the bloom filter false positive rate, however.  I'd like to understand if the loss of privacy is important before making that change.  Thoughts?

Thanks again!

Ken

**Comment by haraldh** [comment]
Well, currently bitcoinj is a little bit broken regarding false positives and the false positive trend it calculates. Upon replaying, I see a force recalculation of the bloom filter very often and sometimes it even disables the filter because of that. By making the bloom filter more tight, we transfer less bytes (good for your data rate).

Regarding security, well, if the NSA wants to find out about my HDW addresses, it's easier for them to get into my phone, than to calculate them from my bloom filters.

When no HDW existed, people reused the same public addresses over and over. So collecting different bloom filters for the same addresses restricts the number space more and more.

Nowadays the change is sent to a new address, so the old bloom filter is extended and let's through even more addresses.

Frankly I don't feel the danger here. But we were wrong about the dimensions of the NSA spying on us, too.

So, do as you like. Personally I take the faster replay and less data volume right now.

An improvement could be to remove the "private" change addresses as soon as they are used and empty, so the amount of keys for bloom filter would shrink, giving a better false positive rate.

**Comment by ksedgwic** [comment]
Harald,

I've added the bloom filter false positive reduction as an experimental mode setting.

You can toggle experimental mode by clicking on the walrus in the About screen 10 times.

I also added check boxes for the setting to the restore and pairing screens since the setting activity isn't available in the flow at that point.

**Pull request merged**
